### ISSUE TITLE
Symlinks support

### ISSUE THREAD

**Issue by hythm7** [frithnanth/perl6-Archive-Libarchive#11]
Is symlink file type supported? 

When archiving a symlink i get the link target data  in the archive not symlink file type.

**Comment by frithnanth** [comment]
Just released on GitHub a new version which takes care of symlinks automatically (see the documentation of method `write-header`).
I uploaded it on the CPAN, but it will take some hours to get to the main servers.

**Comment by hythm7** [comment]
Wow, that was quick. Thank you!

**Comment by frithnanth** [comment]
I forgot to tell you to take a look at the new version of `examples/archive.p6` or `examples/archive-nofilter.p6` for an example on how to assign the proper `filetype`; that cannot be automatic, since one might want to change it while archiving the files.

**Comment by hythm7** [comment]
makes sense. tested and worked for me. Thanks.
