### ISSUE TITLE
Best way to get the filetype of an entry in an archive?

### ISSUE THREAD

**Issue by sdondley** [frithnanth/perl6-Archive-Libarchive#15]
I'm reading the entries in an archive. I'm only interested in the entries that are file names, not directories.

I can use the filetype method on the entry object: `$entry.filetype` and I get what looks like an Int. I get `16384` for a directory and `32768` for a file. 

But I don't know if these numbers might be different on a different machine. I looked for constants in the Raku module code but didn't find any.

Another possible way to check for whether a directory is a directory is to check to see if the last character is a `/`. But again, I'm not 100% sure this will work across all machine types.

It would be nice if the `filetype` method returned something more intuitive or there were some other method to get the type for an entry.

Thanks.

**Comment by frithnanth** [comment]
Thanks for asking.
The file type can be decoded using the AE_* constants defined in Archive::Libarchive::Raw::Constants, anyway I recognize that it's not the best way to decode the file type, so I added some subroutines `is-file`, `is-dir`, etc.
I uploaded new version 0.0.17 to the ecosystem; it should be available soon.
