### ISSUE TITLE
Is there a method/example to read the content of each entry in the archive?

### ISSUE THREAD

**Issue by ohmycloud** [frithnanth/perl6-Archive-Libarchive#6]
The code below just print out the filenames in the archive:

```perl6
my $a = Archive::Libarchive.new: operation => LibarchiveRead, file => $msg.payload;
my Archive::Libarchive::Entry $e .= new;
while $a.next-header($e) {
    $e.pathname.say;
    $a.data-skip;
}
```

which print out:

```
result.txt
log.txt
```

I want to read the content of `result.txt` and `log.txt` but don't want to uncompress the `.tag.gz` file.  The method `!copy-data` seems the right answer, but it's a private method, so is there a method/example to read the content of each entry in the archive?

**Comment by frithnanth** [comment]
No, `!copy-data` won't do it: it just copies between two entries. The problem is that it uses a pointer to a C data block, which is not anything a Perl6 program could use.
I will try to concoct something to bridge the two languages; I'll let you know if I succeed.

**Comment by frithnanth** [comment]
I had to add a new dependency, NativeHelpers::Blob, needed to convert from Pointer to Buf.
The new method `read-file-content` returns the file content in a Buf.
There's a new program `examples/readfile.p6` that demonstrates the new method.
Get it fresh from github, or wait till the CPAN propagates the new version (24 hours tops).

**Comment by ohmycloud** [comment]
You're  really quick!  Thank you very much! It solved my question.
