### ISSUE TITLE
Example for stripping leading directories

### ISSUE THREAD

**Issue by hythm7** [frithnanth/perl6-Archive-Libarchive#8]
How to strip leading directories before archiving a file? for example:

file before archiving    :  /tmp/dir/file
file inside the archive :   dir/file

**Comment by frithnanth** [comment]
So far there was no way to do that using this high-level module - one had to resort to the low-level Archive::Libarchive::Raw - but I've just added a new `pathname` option to the `.write-header()` method.
Now you can do this, for example:
```perl6
sub MAIN($fileo! where { ! .IO.f || die "file '$fileo' already present" },
         *@filei where { $_.all ~~ .IO.f || die "One of ( $_ ) not found" } )
{
  my Archive::Libarchive $a .= new: operation => LibarchiveWrite, file => $fileo;
  for @filei -> $file {
    try {
      $a.write-header($file, uname => 'user1', gname => 'group1', pathname => $file.IO.basename);
      $a.write-data($file);
      CATCH {
        default { .Str.say }
      }
    }
  }
  $a.close;
}
```
You can install the new version 0.0.11 from GitHub, or wait until it hits the CPAN.

**Comment by hythm7** [comment]
Great, Thank you!
